# the version of the platform our pipeline:
version: 2.1

#the instructions created by CircleCi :
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
  
#groups of commands that we want to run:
jobs:
  build:
    docker:
      - image: "cimg/node:16.13.2"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      
#installing dependancies:
      - run:
          name: Install frontend dependencies
          command: npm run frontend:install       
        
      - run:
          name: Install backend dependencies
          command: npm run backend:install
          #Building and Deploying the App              
      - run:
          name: Building Front-End 
          command: npm run frontend:build
      - run:
          name: Building Back-End 
          command: npm run backend:build            
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
            
#instructions about the order of the jobs            
workflows:
  Deploy:                  
    jobs:
      - build:  
          filters:
            branches:
               only:                
                  - main